sonar.projectKey=kevinmlsilva_lore-fork
sonar.organization=kevinmlsilva

sonar.projectName=lore-fork
sonar.projectVersion=0.8.4-nightly

sonar.sources=.
sonar.exclusions=target/**,vendor/**,**/*.pb.rs
